package ooppp_project;

import java.awt.Color;
import java.awt.ComponentOrientation;
import static java.lang.Math.abs;
import static java.lang.Math.ceil;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import table.*;
import scroll.*;
//

public class adminShowTicketHistory extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public adminShowTicketHistory() {
        initComponents();
        this.setResizable(false);
        buses obj = new buses();
        getBusInfo();
        getContentPane().setBackground(Color.WHITE);
        TableCustom.apply(jScrollPaneBusList, TableCustom.TableType.MULTI_LINE);

//        jTableBusList.setShowHorizontalLines(true); // only HorizontalLines
//        jTableBusList.setShowVerticalLines(true); //  only VerticalLines
//        jTableBusList.setShowGrid(true);          // show Horizontal and Vertical
//        jTableBusList.setGridColor(Color.BLUE);
  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneBusList = new javax.swing.JScrollPane();
        jTableHistory = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\bus logo1.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 96));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 102), new java.awt.Color(0, 255, 204), null, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 410, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Search");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 570, 60));

        jTableHistory.setFont(new java.awt.Font("Open Sans Medium", 0, 18)); // NOI18N
        jTableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket NO", "BUS NAME", "PASSENGER", "CONTACT", "FROM", "TO", "COST"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHistory.setFocusable(false);
        jScrollPaneBusList.setViewportView(jTableHistory);
        if (jTableHistory.getColumnModel().getColumnCount() > 0) {
            jTableHistory.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableHistory.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        jPanel1.add(jScrollPaneBusList, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 870, 490));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        adminHome back=new adminHome();
        back.setVisible(true);
        back.pack();
        back.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTableHistory.getModel();
        TableRowSorter<DefaultTableModel> sortTable = new TableRowSorter<>(tblModel);
        jTableHistory.setRowSorter(sortTable);
        sortTable.setRowFilter(RowFilter.regexFilter(search.getText()));
    }//GEN-LAST:event_searchKeyReleased
           
    void getBusInfo(){
        String queryRead = "select * from ticketHistoy";      
        Connection con = JDBC.getConnection();
        DefaultTableModel tblModel = (DefaultTableModel)jTableHistory.getModel();
            try{
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(queryRead);
                while(rs.next()){
                    tblModel.addRow(new Object[]{String.valueOf(rs.getInt("ticketNo")),rs.getString("busname"),
                      rs.getString("passenger"), rs.getString("contact"),rs.getString("fromp"),rs.getString("top"),String.valueOf(rs.getInt("cost"))});
                }
            }
            catch(SQLException e){
                        System.out.println("Error while storing data from Bus."+e.getMessage());
                    }
            catch(Exception e){
                System.out.println("Error while...."+e.getMessage());
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminShowTicketHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminShowTicketHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminShowTicketHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminShowTicketHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new adminShowTicketHistory().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneBusList;
    public static javax.swing.JTable jTableHistory;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables

    void setEditable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
