package ooppp_project;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class adminHome extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public adminHome() {
        initComponents();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnAddBus = new javax.swing.JButton();
        btnShowBusInfo = new javax.swing.JButton();
        btnShowBusInfo1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        left.setForeground(new java.awt.Color(204, 51, 255));
        left.setPreferredSize(new java.awt.Dimension(400, 500));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear.png"))); // NOI18N
        jButton2.setText("UPDATE BUS PATH");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 51, 255)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        left.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, 50));

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money-saving.png"))); // NOI18N
        jButton4.setText("UPDATE COST/KM");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 51, 255)));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        left.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 280, 50));

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton5.setText("DELETE BUS");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 51, 255)));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        left.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 280, 50));

        btnAddBus.setBackground(new java.awt.Color(0, 153, 255));
        btnAddBus.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        btnAddBus.setForeground(new java.awt.Color(255, 255, 255));
        btnAddBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btnAddBus.setText("ADD NEW BUS");
        btnAddBus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 51, 255)));
        btnAddBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddBus.setFocusPainted(false);
        btnAddBus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBusActionPerformed(evt);
            }
        });
        left.add(btnAddBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 280, 50));

        btnShowBusInfo.setBackground(new java.awt.Color(0, 153, 255));
        btnShowBusInfo.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        btnShowBusInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnShowBusInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        btnShowBusInfo.setText("SHOW BUS INFO");
        btnShowBusInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 51, 255)));
        btnShowBusInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowBusInfo.setFocusPainted(false);
        btnShowBusInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnShowBusInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBusInfoActionPerformed(evt);
            }
        });
        left.add(btnShowBusInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, 50));

        btnShowBusInfo1.setBackground(new java.awt.Color(0, 153, 255));
        btnShowBusInfo1.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        btnShowBusInfo1.setForeground(new java.awt.Color(255, 255, 255));
        btnShowBusInfo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticket.png"))); // NOI18N
        btnShowBusInfo1.setText("TICKET HISTORY");
        btnShowBusInfo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 51, 255)));
        btnShowBusInfo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowBusInfo1.setFocusPainted(false);
        btnShowBusInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnShowBusInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBusInfo1ActionPerformed(evt);
            }
        });
        left.add(btnShowBusInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 280, 50));

        jPanel1.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 370, 450));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus logo1.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LOG OUT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 110, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADMIN");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 230, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 635));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateBus updateBusFrame=new updateBus();
        updateBusFrame.setVisible(true);
        updateBusFrame.pack();
        updateBusFrame.setLocationRelativeTo(null);
        this.dispose();
           
       


        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Are you sure?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                adminLogin adminloginFrame=new adminLogin();
                adminloginFrame.setVisible(true);
                adminloginFrame.pack();
                adminloginFrame.setLocationRelativeTo(null);
                this.dispose();
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        updateCost updateCostFrame=new updateCost();
        updateCostFrame.setVisible(true);
        updateCostFrame.pack();
        updateCostFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        deleteBus deleteBusFrame = new deleteBus();
            deleteBusFrame.setVisible(true);
            deleteBusFrame.pack();
            deleteBusFrame.setLocationRelativeTo(null);
            dispose();
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAddBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBusActionPerformed
        // TODO add your handling code here:
             NewBus newBusFrame = new NewBus();
            newBusFrame.setVisible(true);
            newBusFrame.pack();
            newBusFrame.setLocationRelativeTo(null);
            dispose();
        
    }//GEN-LAST:event_btnAddBusActionPerformed

    private void btnShowBusInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBusInfoActionPerformed
        // TODO add your handling code here:
        adminShowBusInfo adminShowBusInfoFrame = new adminShowBusInfo();
            adminShowBusInfoFrame.setVisible(true);
            adminShowBusInfoFrame.pack();
            adminShowBusInfoFrame.setLocationRelativeTo(null);
            dispose();
        
        
    }//GEN-LAST:event_btnShowBusInfoActionPerformed

    private void btnShowBusInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBusInfo1ActionPerformed
        // TODO add your handling code here:
        adminShowTicketHistory adminShowTicketHistoryFrame = new adminShowTicketHistory();
            adminShowTicketHistoryFrame.setVisible(true);
            adminShowTicketHistoryFrame.pack();
            adminShowTicketHistoryFrame.setLocationRelativeTo(null);
            dispose();
    }//GEN-LAST:event_btnShowBusInfo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBus;
    private javax.swing.JButton btnShowBusInfo;
    private javax.swing.JButton btnShowBusInfo1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel left;
    // End of variables declaration//GEN-END:variables
}
