package ooppp_project;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class busList extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public busList() {
        initComponents();
        UserIcon.setText(login.loginUser.getUser());
        this.setResizable(false);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBusName = new javax.swing.JTextField();
        txtBusCost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBusTo = new javax.swing.JTextField();
        btnPayment = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtBusFrom = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        UserIcon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPath = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus logo1.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 122, 110));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LOG OUT");
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 20, 110, 30));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("Bus, You Have Chosen: ");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 310, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUS NAME: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 200, 37));

        txtBusName.setEditable(false);
        txtBusName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBusName.setFocusable(false);
        txtBusName.setRequestFocusEnabled(false);
        txtBusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtBusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 330, 50));

        txtBusCost.setEditable(false);
        txtBusCost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBusCost.setFocusable(false);
        txtBusCost.setRequestFocusEnabled(false);
        jPanel1.add(txtBusCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 170, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("COST (TK):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 81, 37));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Path:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 108, 37));

        txtBusTo.setEditable(false);
        txtBusTo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBusTo.setFocusable(false);
        txtBusTo.setRequestFocusEnabled(false);
        txtBusTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusToActionPerformed(evt);
            }
        });
        jPanel1.add(txtBusTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 310, 240, 50));

        btnPayment.setBackground(new java.awt.Color(51, 255, 255));
        btnPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPayment.setText("GO FOR PAYMENT");
        btnPayment.setFocusPainted(false);
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 270, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("FROM :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 108, 37));

        txtBusFrom.setEditable(false);
        txtBusFrom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBusFrom.setFocusable(false);
        txtBusFrom.setRequestFocusEnabled(false);
        txtBusFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusFromActionPerformed(evt);
            }
        });
        jPanel1.add(txtBusFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 260, 50));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 100, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("AT Service");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 230, 50));

        UserIcon.setEditable(false);
        UserIcon.setBackground(new java.awt.Color(0, 0, 255));
        UserIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserIcon.setForeground(new java.awt.Color(255, 255, 255));
        UserIcon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
        UserIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIconActionPerformed(evt);
            }
        });
        jPanel1.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 200, 40));

        txtPath.setEditable(false);
        txtPath.setColumns(5);
        txtPath.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPath.setRows(5);
        txtPath.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPath);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 540, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Are you sure?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                login loginFrame=new login();
                loginFrame.setVisible(true);
                loginFrame.pack();
                loginFrame.setLocationRelativeTo(null);
                this.dispose();
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtBusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBusNameActionPerformed

    private void txtBusToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusToActionPerformed

        

        public static String BName;
        public static String BCost;
        public static String BFrom;
        public static String BTo;
    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        
      BName = txtBusName.getText();      
      BFrom = txtBusFrom.getText();      
      BTo = txtBusTo.getText();
      BCost = txtBusCost.getText();
      
        payment paymentFrame = new payment();
        paymentFrame.setVisible(true);
        paymentFrame.setLocationRelativeTo(null);
        
            paymentFrame.txtPay.setText(txtBusCost.getText());
        this.dispose();
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void txtBusFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusFromActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FindBus back=new FindBus();
        back.setVisible(true);
        back.pack();
        back.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void UserIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField UserIcon;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtBusCost;
    public static javax.swing.JTextField txtBusFrom;
    public static javax.swing.JTextField txtBusName;
    public static javax.swing.JTextField txtBusTo;
    public static javax.swing.JTextArea txtPath;
    // End of variables declaration//GEN-END:variables

    void setEditable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
