package ooppp_project;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
class btn{
    
}
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public Ticket() {
        initComponents();
        UserIcon.setText(login.loginUser.getUser());
        this.setResizable(false);
                 System.out.println(""+String.valueOf(JDBC.getTicketCount()+1));
           makeTicket();
    }
    void makeTicket(){
        
        txtSL.setText("SL: "+String.valueOf(JDBC.getTicketCount()+1));  
        System.out.println(""+busList.BName
        +busList.BFrom
                +busList.BCost 
                );
        JDBC.insertTableHistory(JDBC.getTicketCount()+1, busList.BName, login.loginUser.getUser(), 
                login.loginUser.getUserCell(), 
                busList.BFrom, busList.BTo, Integer.parseInt(busList.BCost));
         System.out.println("ok");
        txtBusName.setText(busList.BName);                
            txtFrom.setText(busList.BFrom);
            txtTo.setText(busList.BTo);                
            txtCost.setText(busList.BCost);  
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
                 LocalDateTime now = LocalDateTime.now();  
                System.out.println(""+dtf.format(now));
                String a = dtf.format(now);
                 Ticket.txtTime.setText(a);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BkashPay = new javax.swing.JPanel();
        txtFrom = new javax.swing.JTextField();
        txtBusName = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        txtTo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        TICKET = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        UserIcon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BkashPay.setBackground(new java.awt.Color(102, 255, 204));
        BkashPay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BkashPay.setForeground(new java.awt.Color(255, 0, 0));
        BkashPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFrom.setEditable(false);
        txtFrom.setBackground(new java.awt.Color(255, 255, 255));
        txtFrom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFrom.setFocusable(false);
        BkashPay.add(txtFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 226, 42));

        txtBusName.setEditable(false);
        txtBusName.setBackground(new java.awt.Color(255, 255, 255));
        txtBusName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBusName.setFocusable(false);
        txtBusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusNameActionPerformed(evt);
            }
        });
        txtBusName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusNameKeyTyped(evt);
            }
        });
        BkashPay.add(txtBusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 226, 42));

        btnConfirm.setBackground(new java.awt.Color(0, 255, 255));
        btnConfirm.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnConfirm.setText("GO BACK TO HOME");
        btnConfirm.setBorder(new javax.swing.border.MatteBorder(null));
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnConfirm.setFocusCycleRoot(true);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        BkashPay.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 240, 50));

        txtTo.setEditable(false);
        txtTo.setBackground(new java.awt.Color(255, 255, 255));
        txtTo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTo.setFocusable(false);
        txtTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToActionPerformed(evt);
            }
        });
        BkashPay.add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 226, 42));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Cost:");
        BkashPay.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 40));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Bus Name:");
        BkashPay.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 40));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("FROM:");
        BkashPay.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 40));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("TO:");
        BkashPay.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 40));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Time:");
        BkashPay.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 80, 40));

        txtCost.setEditable(false);
        txtCost.setBackground(new java.awt.Color(255, 255, 255));
        txtCost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCost.setFocusable(false);
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });
        BkashPay.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 226, 42));

        txtTime.setEditable(false);
        txtTime.setBackground(new java.awt.Color(255, 255, 255));
        txtTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTime.setFocusable(false);
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        BkashPay.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 226, 42));

        jPanel1.add(BkashPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 410, 400));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus logo1.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 122, 110));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LOG OUT");
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 101, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 100, -1));

        TICKET.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        TICKET.setForeground(new java.awt.Color(255, 255, 255));
        TICKET.setText("TICKET");
        TICKET.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(TICKET, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 150, 60));

        txtSL.setEditable(false);
        txtSL.setBackground(new java.awt.Color(255, 255, 255));
        txtSL.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtSL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSL.setFocusable(false);
        txtSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLActionPerformed(evt);
            }
        });
        txtSL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSLKeyTyped(evt);
            }
        });
        jPanel1.add(txtSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 200, -1));

        UserIcon.setEditable(false);
        UserIcon.setBackground(new java.awt.Color(0, 0, 255));
        UserIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserIcon.setForeground(new java.awt.Color(255, 255, 255));
        UserIcon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
        UserIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIconActionPerformed(evt);
            }
        });
        jPanel1.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Are you sure?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                login loginFrame=new login();
                loginFrame.setVisible(true);
                loginFrame.pack();
                loginFrame.setLocationRelativeTo(null);
                this.dispose();
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtToActionPerformed

    private void txtBusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusNameActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
      
            int res = JOptionPane.showConfirmDialog(this, "Sure to go Home Page?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                FindBus back=new FindBus();
                back.setVisible(true);
                back.pack();
                back.setLocationRelativeTo(null);
                this.dispose();
            }
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "If you go back your chosen path will be removed, Are you sure?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                FindBus back=new FindBus();
                back.setVisible(true);
                back.pack();
                back.setLocationRelativeTo(null);
                this.dispose();
            }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtBusNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusNameKeyTyped

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLActionPerformed

    private void txtSLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSLKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLKeyTyped

    private void UserIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ticket().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BkashPay;
    private javax.swing.JLabel TICKET;
    public static javax.swing.JTextField UserIcon;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtBusName;
    public static javax.swing.JTextField txtCost;
    public static javax.swing.JTextField txtFrom;
    public static javax.swing.JTextField txtSL;
    public static javax.swing.JTextField txtTime;
    public static javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables

    void setEditable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
