package ooppp_project;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class updateCost extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public updateCost() {
        initComponents();
        this.setResizable(false);
        addItmToJComboBusName();
    }
    void addItmToJComboBusName(){
        AutoCompleteDecorator.decorate(jCBBusName);
        //jCBBusName.removeAllItems();
        //jCBBusName.setSelectedIndex(-1);
        Connection con ;
        Statement st;
        ResultSet rs;
        try {
            con = JDBC.getConnection();
            st = con.createStatement();
            rs = st.executeQuery("Select * from Buslist");
            while(rs.next()){
                jCBBusName.addItem(rs.getString("BusName"));
            }
        } catch (Exception e) {
            System.out.println(""+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCBBusName = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        left.setForeground(new java.awt.Color(204, 51, 255));
        left.setPreferredSize(new java.awt.Dimension(400, 500));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setBackground(new java.awt.Color(0, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 204), new java.awt.Color(255, 0, 204)));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        left.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, 50));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel2.setText("Bus Name: ");
        left.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, 30));

        txtCost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });
        left.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 280, 50));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel5.setText("New Cost (/KM): ");
        left.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 160, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel7.setText("---------------------------------------------------------------");
        left.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 460, 30));

        jCBBusName.setFont(new java.awt.Font("Open Sans Medium", 0, 18)); // NOI18N
        jCBBusName.setToolTipText("");
        jCBBusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBBusNameActionPerformed(evt);
            }
        });
        jCBBusName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCBBusNameKeyTyped(evt);
            }
        });
        left.add(jCBBusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 280, 50));

        jPanel1.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 560, 290));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("UPDATE COST");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 260, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus logo1.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LOG OUT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 20, 110, 30));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(!((String)jCBBusName.getSelectedItem()).equals("") && !txtCost.getText().equals("")){
            int res = JOptionPane.showConfirmDialog(this, "Are you sure to update?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                Connection conn;
                Statement st;
                
                //String queryToRead ="select * from BusList where busname = '"+txtBusName.getText()+"'";
                String queryToUpdate = "update buslist set cost = "+txtCost.getText()+" where busname = '"+
                        (String)jCBBusName.getSelectedItem()+"'";
                try {
                    conn= JDBC.getConnection();
                    st = conn.createStatement();
                    st.execute(queryToUpdate);
                   // if(rs.next()){
                        JOptionPane.showMessageDialog(this,"Bus record has been updated.");
                        adminHome adminHomeFrame = new adminHome();
                        adminHomeFrame.setVisible(true);
                        adminHomeFrame.pack();
                        adminHomeFrame.setLocationRelativeTo(null);
                        dispose();
                   // }
                } catch (Exception e) {
                    System.out.println(""+e.getMessage());
                }
            }
            else if(res==1){
            }
        }
        else{
             JOptionPane.showMessageDialog(this,"Please fill all of the textfield!");
       }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Are you sure?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                adminLogin adminloginFrame=new adminLogin();
                adminloginFrame.setVisible(true);
                adminloginFrame.pack();
                adminloginFrame.setLocationRelativeTo(null);
                this.dispose();
            }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        adminHome back=new adminHome();
        back.setVisible(true);
        back.pack();
        back.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jCBBusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBBusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBBusNameActionPerformed

    private void jCBBusNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBBusNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBBusNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new updateCost().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCBBusName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel left;
    public javax.swing.JTextField txtCost;
    // End of variables declaration//GEN-END:variables
}
