package ooppp_project;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
class btn{
    
}
public class payment extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public static String code;
    public payment() {
        
        initComponents();
        UserIcon.setText(login.loginUser.getUser());
        this.setResizable(false);
        
        hereCode.setVisible(false);
        txtCode.setEditable(false);
        txtCode.setFocusable(false);
        btnConfirm.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BkashPay = new javax.swing.JPanel();
        txtBkashPass = new javax.swing.JPasswordField();
        txtPay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGetCode = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBkashNum = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        hereCode = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        UserIcon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BkashPay.setBackground(new java.awt.Color(255, 102, 102));
        BkashPay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BkashPay.setForeground(new java.awt.Color(255, 0, 0));
        BkashPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBkashPass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBkashPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBkashPassActionPerformed(evt);
            }
        });
        txtBkashPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBkashPassKeyTyped(evt);
            }
        });
        BkashPay.add(txtBkashPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 220, 40));

        txtPay.setEditable(false);
        txtPay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPay.setFocusable(false);
        BkashPay.add(txtPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 226, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pin (5digits):");
        BkashPay.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 108, 37));

        btnGetCode.setBackground(new java.awt.Color(255, 255, 102));
        btnGetCode.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnGetCode.setText("GET CODE");
        btnGetCode.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 255, 255), new java.awt.Color(51, 102, 255)));
        btnGetCode.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnGetCode.setFocusCycleRoot(true);
        btnGetCode.setFocusPainted(false);
        btnGetCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCodeActionPerformed(evt);
            }
        });
        BkashPay.add(btnGetCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 100, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BKash Number:");
        BkashPay.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 136, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Paying (TK):");
        BkashPay.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 108, 37));

        txtBkashNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBkashNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBkashNumActionPerformed(evt);
            }
        });
        txtBkashNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBkashNumKeyTyped(evt);
            }
        });
        BkashPay.add(txtBkashNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 226, 42));

        btnConfirm.setBackground(new java.awt.Color(0, 255, 255));
        btnConfirm.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(0, 102, 255));
        btnConfirm.setText("CONFIRM PAY");
        btnConfirm.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 255, 255), new java.awt.Color(51, 102, 255)));
        btnConfirm.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnConfirm.setFocusCycleRoot(true);
        btnConfirm.setFocusPainted(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        BkashPay.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 190, 40));

        hereCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hereCode.setForeground(new java.awt.Color(255, 255, 255));
        hereCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hereCode.setText("Code:");
        BkashPay.add(hereCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 108, 37));

        txtCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        BkashPay.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 110, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Code:");
        BkashPay.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 108, 37));

        jPanel1.add(BkashPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 410, 350));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus logo1.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 122, 110));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LOG OUT");
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 101, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Complete this process to get ticket: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 570, 90));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 100, -1));

        UserIcon.setEditable(false);
        UserIcon.setBackground(new java.awt.Color(0, 0, 255));
        UserIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserIcon.setForeground(new java.awt.Color(255, 255, 255));
        UserIcon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
        UserIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIconActionPerformed(evt);
            }
        });
        jPanel1.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Are you sure?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                login loginFrame=new login();
                loginFrame.setVisible(true);
                loginFrame.pack();
                loginFrame.setLocationRelativeTo(null);
                this.dispose();
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodeActionPerformed

    private void btnGetCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCodeActionPerformed
        // TODO add your handling code here:
        if(txtBkashNum.getText().length()!=11){
            JOptionPane.showMessageDialog(this,"Enter 11digit phone number");
        }
        else{
            JOptionPane.showMessageDialog(this,"Code has been sent to your mobile number.");
            int min = 1000;  
            int max = 9999;     
            System.out.print("Random value of type int between "+min+" to "+max+ ": ");   
             int c = (int)(Math.random()*(max-min+1)+min);  
            code = String.valueOf(c);
            hereCode.setText(code);
            System.out.print(code);  
            
            btnGetCode.setVisible(false); 
            
            hereCode.setVisible(true);
            txtCode.setEditable(true);
            txtCode.setFocusable(true);
            btnConfirm.setEnabled(true);
        }
    }//GEN-LAST:event_btnGetCodeActionPerformed

    private void txtBkashNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBkashNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBkashNumActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        if(txtBkashNum.getText().length()!=11){
            JOptionPane.showMessageDialog(this,"Enter 11digit phone number");
        }
        else if(txtBkashPass.getText().length()!=5){    
            JOptionPane.showMessageDialog(this,"Enter 5digit pin number");
        }
        else if(txtCode.getText()!=code){    
            JOptionPane.showMessageDialog(this,"Enter correct code");
        }
        else{
            int res = JOptionPane.showConfirmDialog(this, "Are you sure to pay?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                JOptionPane.showMessageDialog(this,"Successful! Collect your ticket NOW");
               
              
                Ticket obj=new Ticket();
                obj.setVisible(true);
                obj.pack();
                obj.setLocationRelativeTo(null);
                this.dispose();
            }
            else if(res==1){
                txtBkashPass.setText("");  
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "If you go back your chosen path will be removed, Are you sure?", "CONFIRM", JOptionPane.YES_NO_OPTION);
            if(res==0){
                FindBus back=new FindBus();
                back.setVisible(true);
                back.pack();
                back.setLocationRelativeTo(null);
                this.dispose();
            }
            else if(res==1){
            }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtBkashPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBkashPassKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtBkashPassKeyTyped

    private void txtBkashPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBkashPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBkashPassActionPerformed

    private void txtBkashNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBkashNumKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtBkashNumKeyTyped

    private void UserIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new payment().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BkashPay;
    public static javax.swing.JTextField UserIcon;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnGetCode;
    private javax.swing.JLabel hereCode;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtBkashNum;
    private javax.swing.JPasswordField txtBkashPass;
    public javax.swing.JTextField txtCode;
    public javax.swing.JTextField txtPay;
    // End of variables declaration//GEN-END:variables

    void setEditable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
